### ISSUE TITLE
It is failing with yarn 3.0 - no such file or directory, mkdir

### ISSUE THREAD

**Issue by pie6k** [jjangga0214/hasura-cli#61]
When trying to download with yarn 3.0, I get the following error

```log
Downloading Hasura CLI binary v2.0.0-alpha.7 from https://github.com/hasura/graphql-engine/releases/download/v2.0.0-alpha.7/cli-hasura-darwin-amd64


hasura-cli@2.0.0-alpha.7
Error! Failed to install Hasura CLI binary.
Try npm uninstall hasura-cli or yarn remove hasura-cli and then reinstall it.
If the issue occurs repeatedly, check if your network can access https://github.com as the the Hasura CLI binary file is hosted on Github.
You can report the issue on https://github.com/jjangga0214/hasura-cli/issues with error message.
      
node:fs:1023
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, mkdir
    at Object.mkdirSync (node:fs:1023:3)
    at NodeFS.mkdirSync (/Volumes/drive/dev/acapela/monorepo/.pnp.cjs:21380:24)
    at makeCallSync.subPath.subPath (/Volumes/drive/dev/acapela/monorepo/.pnp.cjs:24265:26)
    at ZipOpenFS.makeCallSync (/Volumes/drive/dev/acapela/monorepo/.pnp.cjs:24489:26)
    at ZipOpenFS.mkdirSync (/Volumes/drive/dev/acapela/monorepo/.pnp.cjs:24264:17)
    at VirtualFS.mkdirSync (/Volumes/drive/dev/acapela/monorepo/.pnp.cjs:21697:24)
    at PosixFS.mkdirSync (/Volumes/drive/dev/acapela/monorepo/.pnp.cjs:21697:24)
    at URLFS.mkdirSync (/Volumes/drive/dev/acapela/monorepo/.pnp.cjs:21697:24)
    at Object.<anonymous> (/Volumes/drive/dev/acapela/monorepo/.yarn/unplugged/hasura-cli-npm-2.0.0-alpha.7-ea573a5519/node_modules/hasura-cli/dist/asset.js:22:26)
    at Generator.next (<anonymous>) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT'
}

```

I'm not sure what exactly happens.

```
yarn --version # 3.0.0-rc.2

package.json > hasura-cli > 2.0.0-alpha.7
```

When running `yarn install` > 

```
hasura-cli@npm:2.0.0-alpha.7 couldn't be built successfully (exit code 1, logs can be found here: <LOG PASTED ABOVE>
```

**Comment by jjangga0214** [comment]
Hi, @pie6k ! 
Thanks for reporting the issue!

I will look at the issue when possible, but as I have no experience in yarn 3, it may take some time.
Please let me know if you find any related information or opinion!

Thanks again :)

**Comment by jjangga0214** [comment]
@pie6k 
To my research, I think there is yarn 2, but no 3 officially announced.
Does your issue actually happen by yarn 2?

**Comment by jjangga0214** [comment]
Feel free to open it again if you really think it should be :)
