### ISSUE TITLE
SyntaxError when running hasura command with yarn v2

### ISSUE THREAD

**Issue by DanNeish** [jjangga0214/hasura-cli#63]
I am getting the following error when trying to run the hasura command with yarn v2:

```
yarn hasura
/Users/dan/Projects/playground/test-yarn-2/node_modules/hasura-cli/hasura:1
����


SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

I have tried with both hasura-cli v1.3.3 & 2.0.0-alpha.10

Setup steps:
```
mkdir test-yarn-v2
npm init
yarn set version berry
```
Add `nodeLinker: node-modules` to .yarnrc.yml file
```
yarn install
yarn add hasura-cli
yarn hasura
```

Any ideas on what might be causing this issue?

**Comment by DanNeish** [comment]
I was able to resolve it by manually removing `"use strict";` from the top of the index.js file in the `node_modules/hasura-cli/dist/` folder.

**Comment by jjangga0214** [comment]
@DanNeish Hi! 
I haven't used yarn v2 yet. 

Is this issue still valid? 

Or have you found any useful information since then? 

You can share any 'guess' even if not 100% sure.

**Comment by osdiab** [comment]
I also have this problem. Install `hasura-cli`, just try running it (`yarn run hasura`), it fails

**Comment by osdiab** [comment]
Just tried uninstalling then reinstalling (triggering a fresh build of `hasura-cli`), that didn't change anything

**Comment by osdiab** [comment]
BTW the OP's instructions are pretty straightforward, if you run literally what he said on your machine it seems to happen.

**Comment by DanNeish** [comment]
@jjangga0214 This is still an issue. My current workaround is installing hasura-cli globally which is not ideal.
Were you able to recreate the issue by following the steps I listed in my original post?

**Comment by drojkind** [comment]
Any updates on this issue? Having the exact same problem as @DanNeish

**Comment by jjangga0214** [comment]
@drojkind I plan to resolve this in **near future**. Sorry if this sounds too vague, but I have been using yarn v1 mainly, so need some uncertain time to research and experiment. That's why I labeled this issue as `help wanted`. Actually, I wanted to solve this much rapidly, but had a busy time recently.
Anyway, I certainly say this issue is in my mind with high priority.

**Comment by osdiab** [comment]
just checking in on this, as it's been a while - wondering if anyone has insights into how this may be resolved. thanks!

**Comment by hixus** [comment]
@jjangga0214 any findings on this? Just got hit by this today using yarn 2.

I have `hasura metadata export` as script in package.json and if executed via yarn 2 I get the `SyntaxError: Invalid or unexpected token`. However if I execute the exact same command directly in shell `./node_modules/hasura-cli/hasura metadata export` it works perfectly. This somewhat tells the install itself is not a problem just the execution via yarn 2.

**Comment by hixus** [comment]
actually adding the `./node_modules/hasura-cli/` prefix to all hasura commands in package.json get's this fixed. Dunno if yarn 2 has some special handling that yarn 1 didn't have.

**Comment by osdiab** [comment]
For anyone looking for an alternative, at my company we ended up using the
`asdf` plugin for hasura-cli (https://github.com/gurukulkarni/asdf-hasura)
to install Hasura on our teams' machines instead of the NPM package, which
works well (we were already using `asdf` to install standard NodeJS
versions anyway - this means just one command, `asdf install`, to handle
both dependencies).

Omar

**Comment by Osman-Sodefa** [comment]
A workaround is to add `"hasura": "$(yarn bin hasura)"` to your `package.json` as mentioned here: https://github.com/yarnpkg/berry/issues/882#issuecomment-1061628214

This probably won't work on Windows, though.

**Comment by jwei98** [comment]
Thanks @Osman-Sodefa, ended up using your workaround!
